package com.phish_patrol.model;

import jakarta.persistence.*;

@Entity
@Table(name = "`user`") // backticks escape the reserved keyword
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // autogenerated id
    private Long id;

    @Column(unique = true, nullable = false) // no two users can have the same user, and user is required
    private String username;

    @Column(nullable = false) // stores the hashed passwords, required
    private String passwordHash;
    
    @Column(nullable = false) // changed email to name, required
    private String name;

    @Column(unique = false, nullable = false)   //introduces experience profiles, required
    private String experience;

    public User() {}

    public User(String username, String passwordHash, String name, String experience) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.name = name;
        this.experience = experience;
    }

    // getters and setters
    public Long getId() { return id; }
    public String getUsername() { return username; }
    public String getPasswordHash() { return passwordHash; }
    public String getName() { return name; }
    public String getExperience() { return experience; }

    public void setUsername(String username) { this.username = username; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public void setName(String name) { this.name = name; }
    public void setExperience(String experience) {this.experience = experience; }
}