package com.phish_patrol.model;

import jakarta.persistence.*;

@Entity
@Table(name = "`user`") // backticks escape the reserved keyword
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // autogenerated id
    private Long id;

    @Column(unique = true, nullable = false) // no two users can have the same user, and user is required
    private String username;

    @Column(nullable = false) // stores the hashed passwords, required
    private String passwordHash;
    
    @Column(unique = true) // only one account with each email
    private String email;

    public User() {}

    public User(String username, String passwordHash, String email) {
        this.username = username;
        this.passwordHash = passwordHash;
        this.email = email;
    }

    // getters and setters
    public Long getId() { return id; }
    public String getUsername() { return username; }
    public String getPasswordHash() { return passwordHash; }
    public String getEmail() { return email; }

    public void setUsername(String username) { this.username = username; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public void setEmail(String email) { this.email = email; }
}